import os
import sys


def setVariables():
    print("Setting Variables for execution")
    os.environ['title'] = 'ABC Technology Solutions Pvt Ltd'
    os.environ['title2'] = 'Address line 1'
    os.environ['title3'] = 'Address line 2'
    os.environ['title4'] = 'sales@company.in'
    os.environ['title5'] = 'PAN - ABC1234A TAN - ABC123A/4'
    os.environ['title6'] = 'Salary Slip'
    os.environ['desc1'] = 'For the Period of - '
    os.environ['desc2'] = 'Staff Name: '
    os.environ['desc3'] = 'Month Days: '
    os.environ['desc4'] = 'Department: '
    os.environ['desc5'] = 'Leave Days: '
    os.environ['desc6'] = 'Designation: '
    os.environ['desc7'] = 'Extra Days: '
    os.environ['desc8'] = 'Office: '
    os.environ['desc9'] = 'Present Days: '
    os.environ['center'] = 'Salary Slip'
    os.environ['left'] = 'Earning'
    os.environ['right'] = 'Deductions'
    os.environ['desc10'] = 'Brake Down'
    os.environ['desc11'] = 'Rs'
    os.environ['desc12'] = 'Basic(INR):          '
    os.environ['desc13'] = 'Misc(INR):           '
    os.environ['desc14'] = 'Gross Amount(INR):   '
    os.environ['desc15'] = 'Deductions(INR):     '
    os.environ['desc16'] = 'Net Salary:   '
    os.environ['desc17'] = 'Prepared by: Rahul'
    os.environ['desc18'] = 'Checked by: Rahul'
    os.environ['desc19'] = 'Authorised by: Rahul'
    os.environ['disc1'] = '*This is a computer generated slip and does not require signatures.'
    os.environ['disc2'] = '*Contact us for any details.'
    os.environ['leave'] = 'Leaves'
    os.environ['leave1'] = 'Sick Leave(s): '
    os.environ['leave2'] = 'Casual Leave(s): '
